все загалом відновив, але при спробі кешування баг ( bot = TransportBot(TELEGRAM_BOT_TOKEN) TypeError: TransportBot.__init__() missing 1 required positional argument: 'stops_cache')